### ISSUE TITLE
Monitor shows Time as Invalid Date.NaN

### ISSUE THREAD

**Issue by kevinjwalters** [tomarus/midiseq#3]
I don't normally use the **Monitor** section but I opened it up today as I was getting some good use out of the app and noticed that the time values are broken. They show up as `Invalid Date.NaN`.

**Comment by kevinjwalters** [comment]
Perhaps to state the obivous, I see they are ok on the image on https://github.com/tomarus/midiseq.

**Comment by tomarus** [comment]
Thanks for reporting this. It appears to work fine when running locally but after a build the date is gone.

I will check this out in the next release.

**Comment by kevinjwalters** [comment]
Thanks, the routing has been very useful for my recent experiments with CircuitPython and turning the Circuit Playground Express into a humble little synthesizer mainly as a demonstration of how to work with MIDI. I was planning to mention and recommend your site in an upcoming article as it's very easy to use in the (Chrome) browser.

**Comment by tomarus** [comment]
Thank you very much and i'm glad it has been useful to you too :)

**Comment by tomarus** [comment]
Thanks, i've fixed this today :)
